login:
	aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 521520363775.dkr.ecr.us-east-2.amazonaws.com
build: login
	docker build -t card_payment_provider .
tag: build
	docker tag card_payment_provider:latest 521520363775.dkr.ecr.us-east-2.amazonaws.com/card_payment_provider:${IMAGE_TAG_PREFIX}-${BITBUCKET_BUILD_NUMBER}
push: tag
	docker push 521520363775.dkr.ecr.us-east-2.amazonaws.com/card_payment_provider:${IMAGE_TAG_PREFIX}-${BITBUCKET_BUILD_NUMBER}
dev: login
	docker run -i -e VAULT_ADDR=${VAULT_ADDR}  -e VAULT_NAMESPACE=${VAULT_NAMESPACE}  -e VAULT_APP_ROLE_ID=${VAULT_APP_ROLE_ID}  -e VAULT_APP_SECRET_ID=${VAULT_APP_SECRET_ID} -e K8S_CLUSTER=${PADDY_K8S_CLUSTER} -e AWS_ACCESS_KEY_ID=${PADDY_AWS_ACCESS_KEY_ID} -e AWS_SECRET_ACCESS_KEY=${PADDY_AWS_SECRET_ACCESS_KEY} -e AWS_DEFAULT_REGION=${PADDY_AWS_DEFAULT_REGION} 521520363775.dkr.ecr.us-east-2.amazonaws.com/eshu:${ESHU_VERSION} helm card_payment_provider ${ENV} ${IMAGE_TAG_PREFIX}-${BITBUCKET_BUILD_NUMBER}
staging: login
	docker run -i -e VAULT_ADDR=${VAULT_ADDR}  -e VAULT_NAMESPACE=${VAULT_NAMESPACE}  -e VAULT_APP_ROLE_ID=${VAULT_APP_ROLE_ID}  -e VAULT_APP_SECRET_ID=${VAULT_APP_SECRET_ID} -e K8S_CLUSTER=${DUDU_K8S_CLUSTER} -e AWS_ACCESS_KEY_ID=${DUDU_AWS_ACCESS_KEY_ID} -e AWS_SECRET_ACCESS_KEY=${DUDU_AWS_SECRET_ACCESS_KEY} -e AWS_DEFAULT_REGION=${DUDU_AWS_DEFAULT_REGION} 521520363775.dkr.ecr.us-east-2.amazonaws.com/eshu:${ESHU_VERSION} helm card_payment_provider ${ENV} ${IMAGE_TAG_PREFIX}-${BITBUCKET_BUILD_NUMBER}
deploy: login
	docker run -i -e VAULT_ADDR=${VAULT_ADDR}  -e VAULT_NAMESPACE=${VAULT_NAMESPACE}  -e VAULT_APP_ROLE_ID=${VAULT_APP_ROLE_ID}  -e VAULT_APP_SECRET_ID=${VAULT_APP_SECRET_ID} -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} -e AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION} 521520363775.dkr.ecr.us-east-2.amazonaws.com/eshu:${ESHU_VERSION} deploy card_payment_provider ${ENV} ${IMAGE_TAG_PREFIX}-${BITBUCKET_BUILD_NUMBER}
	# docker run -i -e K8S_CLUSTER=${PROD_K8S_CLUSTER} -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} -e AWS_DEFAULT_REGION=${AWS_PROD_DEFAULT_REGION} -e VAULT_ADDR=${VAULT_ADDR} -e VAULT_NAMESPACE=${VAULT_NAMESPACE} -e VAULT_APP_ROLE_ID=${VAULT_APP_ROLE_ID} -e VAULT_APP_SECRET_ID=${VAULT_APP_SECRET_ID} 521520363775.dkr.ecr.us-east-2.amazonaws.com/eshu:${ESHU_VERSION} helm card_payment_provider ${ENV} ${IMAGE_TAG_PREFIX}-${BITBUCKET_BUILD_NUMBER}
