#!/bin/sh
set -e

usermod -a -G www-data root
php /var/www/html/artisan optimize
php /var/www/html/artisan filament:optimize
php /var/www/html/artisan icons:cache
php /var/www/html/artisan migrate --force
php /var/www/html/artisan queue:restart

service nginx restart
/usr/bin/supervisord -n -c /etc/supervisord.conf &
php-fpm
